### ISSUE TITLE
Can you kindly provide a LAMMPS example?

### ISSUE THREAD

**Issue by ZKC19940412** [bussilab/crescale#1]
Dear developers. Thank you all so much for putting together such a powerful barostat and I am very interested in using it for my simulations with LAMMPS. However, I am quiet new in using LAMMPS. Can you all kindly provide a LAMMPS example using your barostat?

Thank you all so much for the help. 

Best, 
Zekun

**Comment by GiovanniBussi** [comment]
@vdeltatto maybe you have an example for this? Thanks!

**Comment by vdeltatto** [comment]
Hi,
currently you can use the c-rescale barostat in LAMMPS using [this](https://github.com/bussilab/crescale-lammps/tree/patch_2Jul2021_crescale) modified version of the 2 July 2021 official release. You can use the command `fix press/crescale` with the same options of the `fix press/berendsen` command, which are described [here](https://docs.lammps.org/fix_press_berendsen.html). The c-rescale barostat supports the keywords `iso` and `aniso`, as the Berendsen barostat, but also the keyword `tri`, which allows simulations with non-orthogonal boxes (6 degrees of freedom). 

I added a [subdirectory](https://github.com/bussilab/crescale/tree/master/anisotropic/lammps_example) with an example of input file to carry out a simulation using the c-rescale barostat, using the same ice system described in the paper for the anisotropic version.
